import type { NextPage } from 'next'
import Head from 'next/head'
import cx from "classnames"
import MainSection from '../containers/MainSection/MainSection'

const Home: NextPage = () => {
  return (
    <div className={cx("page", "home")}>
      <div className={cx("container"/* , { open } */)}>
      <Head>
        <title>Malamute Cute App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainSection/>
      </div>
    </div>
  )
}

export default Home
